site_name: My Docs
repo_url: https://github.com/aceberg/TryMkDocs
theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: purple
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - git-revision-date
  - search
  - tags:
      enabled: true
      tags_file: tags.md