site_name: My Docs
repo_url: https://github.com/aceberg/MyDocs
repo_name: aceberg/MyDocs
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: light green
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
        
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - search
  - tags:
      tags_file: tags.md
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/
      name: Follow on LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/aceberg/
      name: Follow on GitHub
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/aceberg
      name: Follow on DockerHub
